version: "3"
services:
  mongodb-primary:
    image: 'bitnami/mongodb:4.0.13'
    restart: always
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=mongodb_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=name_age
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:4.0.13'
    restart: always
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.0.13'
    restart: always
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary

  backend_db:
    build: ./backend/db_service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`db.docker.localhost`)"
      - "traefik.http.services.db.loadbalancer.server.port=8080"
    restart: always
    ports:
      - 8080
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter

  backend_cpu:
    build: ./backend/cpu_service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cpu.rule=Host(`cpu.docker.localhost`)"
      - "traefik.http.services.cpu.loadbalancer.server.port=8080"
    restart: always
    ports:
      - 8080

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  traefik:
    image: "traefik:v2.0.0-rc3"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  mongodb_master_data:
    driver: local